name: Actions Workflow


on: 
  schedule: 
    - cron: "0/2 * * * *"
    - cron: "0/3 * * * *"
  pull_request:
    types: [ opened, reopened, closed, assigned ]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: List Files
        run: | 
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA

      - name: Checkout
        uses: actions/checkout@v3

      - name: List After checkout
        run: | 
          pwd
          ls -la

      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Nariman'

      - name: Log Greating Time
        run:  echo "${{ steps.greet.outputs.time }}"
