name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: List Files
        run: | 
          pwd
          ls
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: List After checkout
        run: | 
          pwd
          ls

      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Nariman'

      - name: Log Greating Time
        run:  echo "${{ steps.greet.outputs.time }}"
