name: Container
on: push
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10 
    steps:

      - name: log node version
        run: node -v

      - name: log node version 
        uses: docker://node:12
        with:
          entrypoint: 'node'
          args: '-v'

      - uses: actions/checkout@v3
      - name: run a script 
        uses: docker://node:12
        with:
          entrypoint: ./script.sh
          args: 'Some String'

      # - name: send a slack message
      #   uses: technosophos/slack-notify
      #   env:
      #     SLACK_WEBHOOK: ${{ secret.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "hello slack"


  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: nariman1987/actions
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:

      - name: post user
        run: "curl -X POST http://localhost:3001/api/user 
        -H 'Content-Type: application/json' 
        -d '{\"username\":\"nariman\",\"address\":\"Baku\"}'" 
      
      - name: get users
        run: curl http://localhost:3001/api/users
      