name: Container
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14-alpine
    steps:
      - name: log out node version
        run: | 
          node -v
          cat /etc/os-release