name: Shell comands

on: 
  pull_request: 
  # push:

jobs: 
  run-linux-command: 
    runs-on: ubuntu-latest
    steps:

      - name: echo string
        run: echo "Hello World"
        continue-on-error: true
        timeout-minutes: 2

      - name: echo string
        run: echo "Hello World"
    
      - name: multiline script
        run: | 
          node -v
          npm -v

      - name: python command
        shell: python
        run: | 
          import platform
          print(platform.processor())
  
  run-windows-command:
    needs: ["run-linux-command"]
    runs-on: windows-latest
    steps:
      
      - name: Directory Powershell
        run: Get-Location

      - name: Directory bash
        shell: bash
        run: pwd